# Generated by Django 5.2.7 on 2026-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
